### ISSUE TITLE
博主可以提供一下weibo21的数据集吗？

### ISSUE THREAD

**Issue by dongdong0709** [ICTMCG/GenFEND#3]
我的邮箱是hje0112@bigc.edu.cn，期待您的回信

**Comment by kennqiang** [comment]
数据集已发送到您的邮箱，谢谢关注

**Comment by zkx990429** [comment]
> 我的邮箱是[hje0112@bigc.edu.cn](mailto:hje0112@bigc.edu.cn)，期待您的回信

您好，请问能不能把数据集也发给我一份？我的邮箱是1277767811@qq.com，谢谢

**Comment by wgyhhhh** [comment]
可不可以发我一份数据集wgy3129@stu.ouc.edu.cn，谢谢
